import type { Context, Config } from "@netlify/functions";
import { mutateAppData } from "../../shared/firestore-admin.mts";

// Webhook target for each client's "automatic review replies" GHL workflow
// (Review Received trigger → review-reply action → Custom Webhook step
// pointing here). One ping = one real reply the automation just sent, so
// the count is exact, free (no polling, no gated APIs, no scopes — GHL's
// Private Integration scope list has NO reviews scope, confirmed 2026-07-15),
// and it lands on the client's Monthly SEO Report automatically via the
// activity feed ('review-response' is already in the report's category
// filter).
//
// Auth: shared secret in ?key= (or x-webhook-key header) matching the
// GHL_REVIEW_WEBHOOK_KEY env var — GHL workflows can't do Firebase sign-in.
// Client matching: the workflow payload's locationId → client.ghlLocationId.
// Dedup: GHL retries webhooks on slow responses; a review id (when present
// in the payload) is stored on the activity as sourceId and repeats are
// dropped, so a retry can't double-count.

function json(o: any, status = 200) {
  return new Response(JSON.stringify(o), { status, headers: { "content-type": "application/json" } });
}

function uid(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

// GHL webhook payload shapes vary by trigger/version — probe the common
// spots for each fact instead of trusting one exact schema.
function pick(...vals: any[]): any {
  for (const v of vals) if (v !== undefined && v !== null && v !== "") return v;
  return null;
}

export default async (req: Request, _ctx: Context) => {
  if (req.method !== "POST") return json({ error: "POST only" }, 405);

  const expected = Netlify.env.get("GHL_REVIEW_WEBHOOK_KEY");
  if (!expected) return json({ error: "GHL_REVIEW_WEBHOOK_KEY not configured on the server" }, 500);
  const url = new URL(req.url);
  const provided = url.searchParams.get("key") || req.headers.get("x-webhook-key") || "";
  if (provided !== expected) return json({ error: "Invalid or missing key" }, 401);

  let body: any = {};
  try { body = await req.json(); } catch { /* GHL "test webhook" sends odd/empty bodies — accept them */ }

  const locationId = pick(body.locationId, body.location_id, body.location?.id, body.customData?.locationId);
  if (!locationId) return json({ ok: true, note: "No locationId in payload — nothing logged (test ping?)" });

  const reviewId = pick(body.reviewId, body.review_id, body.review?.id, body.id);
  const rating = pick(body.rating, body.review?.rating, body.reviewRating);
  const reviewer = pick(body.reviewerName, body.reviewer?.name, body.review?.reviewerName, body.contactName, body.fullName);
  const nowIso = new Date().toISOString();
  const text = `Auto-replied to a Google review${rating ? ` (${rating}★)` : ""}${reviewer ? ` from ${reviewer}` : ""}`;

  let result = "logged";
  await mutateAppData((data: any) => {
    const client = (data.clients || []).find((c: any) => (c.ghlLocationId || "").trim() === String(locationId).trim());
    if (!client) { result = `no client with ghlLocationId ${locationId}`; return false; }
    client.activities = client.activities || [];
    if (reviewId && client.activities.some((a: any) => a.category === "review-response" && a.sourceId === String(reviewId))) {
      result = "duplicate — already logged";
      return false;
    }
    client.activities.push({
      id: uid(),
      taskId: "",
      date: nowIso,
      text,
      category: "review-response",
      sourceId: reviewId ? String(reviewId) : undefined,
      autoGenerated: true,
      createdAt: nowIso,
    });
    result = `logged for ${client.name}`;
    return undefined;
  });

  return json({ ok: true, result });
};

export const config: Config = { path: "/api/review-reply-log" };
