// GIT_STATIC commit builder — page-publisher-build-spec.md §1 (atomicity),
// §6d (inbound links in the same commit), §7 (schedule.ts as the single
// source of truth for the go-live date).
//
// ─── Everything here is DERIVED FROM THE REAL REPO, not assumed ───
// Read out of anthonykmartinez01/rankin-waste-management on 2026-07-26:
//
//   Layout:    src/layouts/Layout.astro, default-imported as `Layout`.
//              Props: title (req), description (req), image?, imageAlt?,
//              noindex?. It computes the canonical tag itself from
//              SITE_URL + Astro.url.pathname (astro.config trailingSlash:
//              'never') — so a page must NOT emit its own canonical.
//   Registry:  src/lib/schedule.ts, `export const schedule: Record<string,
//              string>` keyed by normalized path → 'YYYY-MM-DD'.
//   Guard:     three lines at the very top of frontmatter:
//                import { scheduleGuard } from '<depth>/lib/schedule';
//                const guard = scheduleGuard(Astro);
//                if (guard) return guard;
//
// ─── One honest deviation, flagged rather than hidden ───
// The repo has TWO existing page shapes: hand-rolled (abbott.astro composes
// Layout + InnerHero + FaqAccordion directly) and data-driven (watt.astro
// passes a LocationSection[] to a LocationPage component). Our intake
// pipeline produces sanitized HTML, not a LocationSection[] array, so a
// committed page uses Layout + `set:html` — a THIRD shape. Converting HTML
// into LocationSection[] would mean guessing structure the paste doesn't
// carry, which is exactly the kind of silent lossy transform this build has
// avoided elsewhere. The generated file is valid, uses the real layout, and
// gets the real guard; it just isn't the data-driven shape.
import { ghHeaders, parseOwnerRepo } from "../github-schedule.mts";
import { fetchRepoFileContent } from "./adapters/git-static-adapter.mts";
import { isUnsupported } from "./adapters/base-adapter.mts";
import type { PagePublisherPage, PagePublisherSite, PagePublisherImage } from "./firestore.mts";

const SCHEDULE_PATH = "src/lib/schedule.ts";

export interface TreeFile {
  path: string;
  content: string;
  // What this entry is, for the dry-run report
  kind: "new_page" | "schedule_registry" | "inbound_link_edit";
  note: string;
}

// Per-task outcome, so an inbound link that COULDN'T be auto-applied becomes
// a persisted, visible manual task instead of a warning that scrolls past.
// Anthony's requirement (2026-07-26): "the orphan gate blocked at intake, so
// the link was promised; if it can't be auto-applied, I have to be told to do
// it by hand or the page orphans anyway."
export interface TaskOutcome {
  sourceUrl: string;
  anchorText: string;
  applied: boolean;
  reason?: string;
  repoPath?: string;
}

export interface CommitPlan {
  ok: boolean;
  error?: string;
  repo: string;
  branch: string;
  files: TreeFile[];
  taskOutcomes: TaskOutcome[];
  derived: {
    layoutImportPath: string;
    scheduleImportPath: string;
    pageRepoPath: string;
    scheduleKey: string;
    goLiveDate: string | null;
  };
  warnings: string[];
}

function esc(s: string): string {
  return String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Depth-correct relative import prefix for a file at src/pages/a/b/c.astro.
function depthPrefix(pageRepoPath: string, pagesDir: string): string {
  const rel = pageRepoPath.replace(new RegExp("^" + pagesDir.replace(/\/+$/, "") + "/"), "");
  const depth = rel.split("/").length - 1; // 0 for src/pages/foo.astro
  return "../".repeat(depth + 1); // +1 to escape src/pages itself
}

export function buildPageFile(page: PagePublisherPage, images: PagePublisherImage[], layoutRel: string, scheduleRel: string, scheduled: boolean): string {
  const lcp = images.find((i) => i.isLcp);
  const guard = scheduled
    ? `import { scheduleGuard } from '${scheduleRel}';\n\nconst guard = scheduleGuard(Astro);\nif (guard) return guard;\n`
    : "";
  const schemaBlock = page.schemaJsonLd
    ? `\n  <Fragment slot="head">\n    <script is:inline type="application/ld+json" set:html={JSON.stringify(${JSON.stringify(page.schemaJsonLd, null, 6).replace(/\n/g, "\n    ")})} />\n  </Fragment>\n`
    : "";

  return `---
// ${page.slug}.astro
// Generated by KailenFlow Page Publisher. Body content came from the
// operator's paste, sanitized per the build spec's intake pipeline.
${scheduled ? "// Scheduled via src/lib/schedule.ts — the guard below is what hides it until its date.\n" : ""}import Layout from '${layoutRel}';
${guard}---

<Layout
  title="${esc(page.title)}"
  description="${esc(page.metaDescription)}"${lcp?.uploadedRemoteUrl ? `\n  image="${esc(lcp.uploadedRemoteUrl)}"\n  imageAlt="${esc(lcp.altText)}"` : ""}
>${schemaBlock}
  <article set:html={${JSON.stringify(page.htmlBody)}} />
</Layout>
`;
}

// Idempotent edit of the schedule registry: replaces an existing key's date
// rather than appending a duplicate. Returns null when no change is needed.
export function upsertScheduleEntry(source: string, key: string, date: string): { content: string; changed: boolean; action: "added" | "updated" | "unchanged" } {
  const keyRe = new RegExp(`(['"\`])${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\1\\s*:\\s*(['"\`])([^'"\`]*)\\2\\s*,?`);
  const existing = source.match(keyRe);
  if (existing) {
    if (existing[3] === date) return { content: source, changed: false, action: "unchanged" };
    return { content: source.replace(keyRe, `'${key}': '${date}',`), changed: true, action: "updated" };
  }
  // Insert just before the registry's closing brace. Anchored on the real
  // file's shape: `export const schedule: Record<string, string> = { ... };`
  const openIdx = source.search(/export\s+const\s+schedule\s*:\s*Record<string,\s*string>\s*=\s*\{/);
  if (openIdx === -1) return { content: source, changed: false, action: "unchanged" };
  const closeIdx = source.indexOf("};", openIdx);
  if (closeIdx === -1) return { content: source, changed: false, action: "unchanged" };
  const before = source.slice(0, closeIdx);
  const after = source.slice(closeIdx);
  return { content: `${before}  '${key}': '${date}',\n${after}`, changed: true, action: "added" };
}

// Inserts an inbound link into an existing page's source, immediately after
// the first occurrence of an anchor-friendly spot. Deliberately conservative:
// if it can't find a safe insertion point it reports a warning instead of
// mangling a real client file.
export function insertInboundLinkIntoSource(source: string, targetPath: string, anchorText: string): { content: string; inserted: boolean; reason?: string } {
  if (source.includes(`href="${targetPath}"`) || source.includes(`href='${targetPath}'`)) {
    return { content: source, inserted: false, reason: "A link to this page already exists in that file — skipped (idempotent)." };
  }
  // Prefer appending a sentence into the LAST `{ type: 'p', text: \`...\` }`
  // block (the data-driven LocationPage shape), which is the newest
  // convention in this repo and the safest structured insertion point.
  const pBlocks = [...source.matchAll(/\{\s*type:\s*'p',\s*text:\s*`([^`]*)`\s*\}/g)];
  if (pBlocks.length > 0) {
    const last = pBlocks[pBlocks.length - 1];
    const sentence = ` See our <a href="${targetPath}">${anchorText}</a> page for details.`;
    const replaced = `{ type: 'p', text: \`${last[1]}${sentence}\` }`;
    return { content: source.slice(0, last.index!) + replaced + source.slice(last.index! + last[0].length), inserted: true };
  }
  return { content: source, inserted: false, reason: "No safe structured insertion point found in that file — add this link by hand rather than risk mangling it." };
}

export async function buildCommitPlan(page: PagePublisherPage, images: PagePublisherImage[], site: PagePublisherSite): Promise<CommitPlan> {
  const warnings: string[] = [];
  const pagesDir = (site.pagesDir || "src/pages").replace(/\/+$/, "");
  const slug = (page.slug || "").replace(/^\/+|\/+$/g, "");
  const taskOutcomes: TaskOutcome[] = [];
  const plan: CommitPlan = {
    ok: false, repo: site.repo || "", branch: site.branch || "main", files: [], taskOutcomes,
    derived: { layoutImportPath: "", scheduleImportPath: "", pageRepoPath: "", scheduleKey: "", goLiveDate: page.scheduledFor },
    warnings,
  };
  if (!site.repo) return { ...plan, error: "No repo configured for this site." };
  if (!slug) return { ...plan, error: "This page has no slug — can't derive a file path." };

  const pageRepoPath = `${pagesDir}/${slug}.astro`;
  const scheduleKey = "/" + slug;
  const prefix = depthPrefix(pageRepoPath, pagesDir);
  const layoutRel = `${prefix}layouts/Layout.astro`;
  const scheduleRel = `${prefix}lib/schedule`;
  plan.derived = { layoutImportPath: layoutRel, scheduleImportPath: scheduleRel, pageRepoPath, scheduleKey, goLiveDate: page.scheduledFor };

  // 1. The page file
  const scheduled = !!page.scheduledFor;
  plan.files.push({
    path: pageRepoPath,
    content: buildPageFile(page, images, layoutRel, scheduleRel, scheduled),
    kind: "new_page",
    note: scheduled ? "New page, with scheduleGuard (hidden until its date)." : "New page, publishes immediately (no schedule entry).",
  });

  // 2. schedule.ts — only when there's a date. Read the REAL current file.
  if (scheduled) {
    const cur = await fetchRepoFileContent({ id: site.id, clientId: site.clientId, domain: site.domain, repo: site.repo, branch: site.branch, pagesDir: site.pagesDir }, SCHEDULE_PATH);
    if (isUnsupported(cur)) return { ...plan, error: `Could not read ${SCHEDULE_PATH}: ${cur.reason}` };
    const up = upsertScheduleEntry(cur, scheduleKey, page.scheduledFor!);
    if (up.action === "unchanged") {
      warnings.push(`${SCHEDULE_PATH} already has '${scheduleKey}': '${page.scheduledFor}' — no registry change needed (idempotent).`);
    } else {
      plan.files.push({ path: SCHEDULE_PATH, content: up.content, kind: "schedule_registry", note: `Registry entry ${up.action}: '${scheduleKey}': '${page.scheduledFor}'` });
    }
  } else {
    warnings.push("No scheduledFor set — committing without a schedule.ts entry means this page goes live on the next build.");
  }

  // 3. Inbound-link edits, in the SAME commit (§6d atomicity)
  for (const task of page.inboundLinkTasks || []) {
    if (task.status === "applied") { taskOutcomes.push({ sourceUrl: task.sourceUrl, anchorText: task.anchorText, applied: true, reason: "Already applied in an earlier commit." }); continue; }
    const srcPath = await repoPathForUrl(site, task.sourceUrl);
    if (!srcPath) {
      const reason = "Couldn't map that URL to a repo file — add this link by hand.";
      warnings.push(`Inbound link from ${task.sourceUrl}: ${reason}`);
      taskOutcomes.push({ sourceUrl: task.sourceUrl, anchorText: task.anchorText, applied: false, reason });
      continue;
    }
    const cur = await fetchRepoFileContent({ id: site.id, clientId: site.clientId, domain: site.domain, repo: site.repo, branch: site.branch, pagesDir: site.pagesDir }, srcPath);
    if (isUnsupported(cur)) {
      warnings.push(`Inbound link from ${srcPath}: ${cur.reason}`);
      taskOutcomes.push({ sourceUrl: task.sourceUrl, anchorText: task.anchorText, applied: false, reason: cur.reason, repoPath: srcPath });
      continue;
    }
    const res = insertInboundLinkIntoSource(cur, scheduleKey, task.anchorText);
    if (!res.inserted) {
      warnings.push(`Inbound link into ${srcPath}: ${res.reason}`);
      taskOutcomes.push({ sourceUrl: task.sourceUrl, anchorText: task.anchorText, applied: false, reason: res.reason, repoPath: srcPath });
      continue;
    }
    plan.files.push({ path: srcPath, content: res.content, kind: "inbound_link_edit", note: `Adds a link to ${scheduleKey} with anchor "${task.anchorText}".` });
    taskOutcomes.push({ sourceUrl: task.sourceUrl, anchorText: task.anchorText, applied: true, repoPath: srcPath });
  }

  plan.ok = true;
  return plan;
}

async function repoPathForUrl(site: PagePublisherSite, url: string): Promise<string | null> {
  const entry = (site.siteGraph?.pageIndex || {})[url];
  const path = entry?.path;
  if (!path) return null;
  const pagesDir = (site.pagesDir || "src/pages").replace(/\/+$/, "");
  const rel = path.replace(/^\/+/, "");
  return rel === "" ? `${pagesDir}/index.astro` : `${pagesDir}/${rel}.astro`;
}

// ─── The actual atomic commit (Git Trees API) ───
// ONE commit containing every file in the plan. Not page-then-links.
export async function commitPlan(plan: CommitPlan, message: string): Promise<{ ok: boolean; commitSha?: string; error?: string }> {
  const token = Netlify.env.get("GITHUB_TOKEN");
  if (!token) return { ok: false, error: "GITHUB_TOKEN not configured on the server" };
  const parsed = parseOwnerRepo(plan.repo);
  if (!parsed) return { ok: false, error: `Invalid repo "${plan.repo}"` };
  const { owner, repoName } = parsed;
  const headers = ghHeaders(token);
  const api = `https://api.github.com/repos/${owner}/${repoName}`;

  try {
    const refRes = await fetch(`${api}/git/ref/heads/${encodeURIComponent(plan.branch)}`, { headers, cache: "no-store" });
    if (!refRes.ok) return { ok: false, error: `GitHub ${refRes.status} reading branch ${plan.branch}` };
    const baseSha = (await refRes.json()).object.sha;

    const commitRes = await fetch(`${api}/git/commits/${baseSha}`, { headers, cache: "no-store" });
    if (!commitRes.ok) return { ok: false, error: `GitHub ${commitRes.status} reading base commit` };
    const baseTree = (await commitRes.json()).tree.sha;

    const treeRes = await fetch(`${api}/git/trees`, {
      method: "POST", headers,
      body: JSON.stringify({ base_tree: baseTree, tree: plan.files.map((f) => ({ path: f.path, mode: "100644", type: "blob", content: f.content })) }),
    });
    if (!treeRes.ok) return { ok: false, error: `GitHub ${treeRes.status} creating tree: ${(await treeRes.text()).slice(0, 300)}` };
    const newTree = (await treeRes.json()).sha;

    const newCommitRes = await fetch(`${api}/git/commits`, {
      method: "POST", headers,
      body: JSON.stringify({ message, tree: newTree, parents: [baseSha] }),
    });
    if (!newCommitRes.ok) return { ok: false, error: `GitHub ${newCommitRes.status} creating commit` };
    const commitSha = (await newCommitRes.json()).sha;

    const patchRes = await fetch(`${api}/git/refs/heads/${encodeURIComponent(plan.branch)}`, {
      method: "PATCH", headers, body: JSON.stringify({ sha: commitSha }),
    });
    if (!patchRes.ok) return { ok: false, error: `GitHub ${patchRes.status} updating branch ref` };

    return { ok: true, commitSha };
  } catch (e: any) {
    return { ok: false, error: String(e?.message || e) };
  }
}
